testname: Modulation Effects MUSHRA Test
testId: mod_fx_listening_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: generic
  id: first_page
  name: Welcome
  content: Welcome to this listening test on guitar modulation effects. <br><br>In
    this test you will be asked to rate audio clips by how closely they match a reference
    clip. <br><br>There is one training example then 12 tests to complete. It should
    take no longer than 15-20 mins.
- type: mushra
  id: training_ss-A_0
  name: Training example
  content: 'This is a training example to show you how to use the user interface (your
    results will not be recorded). Please read all of the following before continuing
    to the test. <br><br> <strong>MUSHRA</strong> stands for <strong>MU</strong>ltiple
    <strong>S</strong>timuli <strong>H</strong>idden <strong>R</strong>eference and
    <strong>A</strong>nchor <br><br> <strong>YOUR TASK:</strong> rate each Condition
    (or stimulus) below by how closely it sounds like the Reference. <br><br> <strong>IMPORTANT:</strong>
    the Reference itself will <em>always</em> be hidden amongst the Conditions. If
    you identify the hidden reference, you <em>must</em> rate this 100. <br><br> In
    other words, you should always rate <em>at least</em> one clip 100.

    <br><br> In the example below, the clips are labelled (e.g. reference, anchor)
    but this information is hidden in the real test and the conditions are randomised.
    <br><br> Feel free to listen as many times as you need and to loop segments. <br><br>
    Useful keyboard shortcuts: SPACE - play/pause; R - play/pause reference; NUMBERS
    - play/pause condition by number; BACKSPACE - stop.'
  enableLooping: true
  showConditionNames: true
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test/ss/SS-A_clip0_model.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test/input/clip0_input.wav
    C1: configs/resources/audio/mod_fx_listening_test/ss/SS-A_clip0_model.wav
    C2: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip0_reaper.wav
-
  - random
  - type: mushra
    id: test_SS-B_2
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip2_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip2_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip2_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip2_reaper.wav
  - type: mushra
    id: test_SS-B_10
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip10_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip10_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip10_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip10_reaper.wav
  - type: mushra
    id: test_SS-E_5
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/ss/SS-E_clip5_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip5_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/ss/SS-E_clip5_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/ss/SS-E_clip5_reaper.wav
  - type: mushra
    id: test_SS-E_11
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/ss/SS-E_clip11_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip11_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/ss/SS-E_clip11_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/ss/SS-E_clip11_reaper.wav
  - type: mushra
    id: test_SV-1-C_3
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-C_clip3_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip3_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-C_clip3_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-C_clip3_pedalboard.wav
  - type: mushra
    id: test_SV-1-C_9
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-C_clip9_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip9_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-C_clip9_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-C_clip9_pedalboard.wav
  - type: mushra
    id: test_SV-1-E_4
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-E_clip4_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip4_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-E_clip4_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-E_clip4_pedalboard.wav
  - type: mushra
    id: test_SV-1-E_7
    name: TEST IN PROGRESS
    content: 'Rate each condition by how closely it matches the reference. <br><br>
      Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
      rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
      - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
      stop'
    enableLooping: true
    showConditionNames: false
    createAnchor35: false
    createAnchor70: false
    reference: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-E_clip7_target.wav
    stimuli:
      anchor: configs/resources/audio/mod_fx_listening_test/input/clip7_input.wav
      C1: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-E_clip7_model.wav
      C2: configs/resources/audio/mod_fx_listening_test/sv-1/SV-1-E_clip7_pedalboard.wav
- type: mushra
  id: test_BF-2-A_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-A_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test/input/clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-A_clip1_model.wav
    C2: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-A_clip1_pedalboard.wav
- type: mushra
  id: test_BF-2-A_8
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-A_clip8_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test/input/clip8_input.wav
    C1: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-A_clip8_model.wav
    C2: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-A_clip8_pedalboard.wav
- type: mushra
  id: test_BF-2-C_6
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-C_clip6_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test/input/clip6_input.wav
    C1: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-C_clip6_model.wav
    C2: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-C_clip6_pedalboard.wav
- type: mushra
  id: test_BF-2-C_12
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-C_clip12_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test/input/clip12_input.wav
    C1: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-C_clip12_model.wav
    C2: configs/resources/audio/mod_fx_listening_test/bf-2/BF-2-C_clip12_pedalboard.wav
- type: finish
  name: Thank you
  content: Thank you for attending!
  showResults: true
  writeResults: true
  questionnaire:
  - type: text
    label: Name/nickname/email
    name: name
  - type: number
    label: Age
    name: age
    min: 0
    max: 100
    default: 30
