testname: Modulation Effects MUSHRA Test
testId: mod_fx_listening_test
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php
pages:
- type: generic
  id: first_page
  name: Welcome
  content: Welcome to this listening test on guitar modulation effects. <br><br>In
    this test you will be asked to rate audio clips by how closely they match a reference
    clip. <br><br>There is one training example then 15 tests to complete. It should
    take no longer than 15-20 mins.
- type: mushra
  id: training_ss-A_0
  name: Training example
  content: 'This is a training example to show you how to use the user interface (your
    results will not be recorded). Please read all of the following before continuing
    to the test. <br><br> <strong>MUSHRA</strong> stands for <strong>MU</strong>ltiple
    <strong>S</strong>timuli <strong>H</strong>idden <strong>R</strong>eference and
    <strong>A</strong>nchor <br><br> <strong>YOUR TASK:</strong> rate each Condition
    (or stimulus) below by how closely it sounds like the Reference. <br><br> <strong>IMPORTANT:</strong>
    the Reference itself will <em>always</em> be hidden amongst the Conditions. If
    you identify the hidden reference, you <em>must</em> rate this 100. <br><br> In
    other words, you should always rate <em>at least</em> one clip 100.

    <br><br> In the example below, the clips are labelled (e.g. reference, anchor)
    but this information is hidden in the real test and the conditions are randomised.
    <br><br> Feel free to listen as many times as you need and to loop segments. <br><br>
    Useful keyboard shortcuts: SPACE - play/pause; R - play/pause reference; NUMBERS
    - play/pause condition by number; BACKSPACE - stop.'
  enableLooping: true
  showConditionNames: true
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test/ss/SS-A_clip0_model.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test/input/clip0_input.wav
    C1: configs/resources/audio/mod_fx_listening_test/ss/SS-A_clip0_model.wav
    C2: configs/resources/audio/mod_fx_listening_test/ss/SS-B_clip0_reaper.wav
- ''
- random
- type: mushra
  id: test_SS-B_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SS-B_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SS-B_clip1_model_0.wav
- type: mushra
  id: test_SS-B_2
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SS-B_clip2_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip2_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SS-B_clip2_model_0.wav
- type: mushra
  id: test_SS-B_3
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SS-B_clip3_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip3_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SS-B_clip3_model_0.wav
- type: mushra
  id: test_SS-E_3
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SS-E_clip3_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip3_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SS-E_clip3_model_0.wav
- type: mushra
  id: test_SS-E_2
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SS-E_clip2_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip2_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SS-E_clip2_model_0.wav
- type: mushra
  id: test_SS-E_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SS-E_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SS-E_clip1_model_0.wav
- type: mushra
  id: test_SV-1-C_3
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SV-1-C_clip3_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip3_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SV-1-C_clip3_model_0.wav
- type: mushra
  id: test_SV-1-C_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SV-1-C_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SV-1-C_clip1_model_0.wav
- type: mushra
  id: test_SV-1-C_2
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SV-1-C_clip2_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip2_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SV-1-C_clip2_model_0.wav
- type: mushra
  id: test_SV-1-E_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SV-1-E_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SV-1-E_clip1_model_0.wav
- type: mushra
  id: test_SV-1-E_2
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SV-1-E_clip2_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip2_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SV-1-E_clip2_model_0.wav
- type: mushra
  id: test_SV-1-E_3
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/SV-1-E_clip3_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip3_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/SV-1-E_clip3_model_0.wav
- type: mushra
  id: test_BF-2-A_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/BF-2-A_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/BF-2-A_clip1_model_0.wav
- type: mushra
  id: test_BF-2-A_3
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/BF-2-A_clip3_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip3_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/BF-2-A_clip3_model_0.wav
- type: mushra
  id: test_BF-2-A_2
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/BF-2-A_clip2_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip2_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/BF-2-A_clip2_model_0.wav
- type: mushra
  id: test_BF-2-C_2
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/BF-2-C_clip2_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip2_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/BF-2-C_clip2_model_0.wav
- type: mushra
  id: test_BF-2-C_1
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/BF-2-C_clip1_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip1_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/BF-2-C_clip1_model_0.wav
- type: mushra
  id: test_BF-2-C_3
  name: TEST IN PROGRESS
  content: 'Rate each condition by how closely it matches the reference. <br><br>
    Remember: <em>at least</em> one clip <em>must</em> be rated 100. It is okay to
    rate more than one clip 100.<br><br>Keyboard shortcuts: SPACE - play/pause; R
    - play/pause reference; NUMBERS - play/pause condition by number; BACKSPACE -
    stop'
  enableLooping: true
  showConditionNames: false
  createAnchor35: false
  createAnchor70: false
  reference: configs/resources/audio/mod_fx_listening_test_v2/BF-2-C_clip3_target.wav
  stimuli:
    anchor: configs/resources/audio/mod_fx_listening_test_v2/input_clip3_input.wav
    C1: configs/resources/audio/mod_fx_listening_test_v2/BF-2-C_clip3_model_0.wav
- type: finish
  name: Thank you
  content: Thank you for attending!
  showResults: true
  writeResults: true
  questionnaire:
  - type: text
    label: Name/nickname/email
    name: name
  - type: number
    label: Age
    name: age
    min: 0
    max: 100
    default: 30
